-- Ejecuta este SQL en el editor SQL de tu proyecto Supabase
-- (Dashboard Supabase → SQL Editor → New query → pegar y Run)

create table if not exists public.guias_generadas (
  id bigint generated by default as identity primary key,
  num_guia int not null,
  pedidos text not null,
  created_at timestamptz default now()
);

create index if not exists idx_guias_generadas_pedidos on public.guias_generadas (pedidos);

-- Opcional: permitir que la API (service_role o anon) inserte/consulte/borre
-- (ajusta según tus políticas RLS si usas autenticación)
alter table public.guias_generadas enable row level security;

drop policy if exists "Allow all for guias_generadas" on public.guias_generadas;
create policy "Allow all for guias_generadas"
  on public.guias_generadas for all
  using (true)
  with check (true);

-- Historial operativo de guías (últimos 2 meses en UI)
create table if not exists public.guias_historial (
  id bigint generated by default as identity primary key,
  pedido text,
  parte int not null default 1,
  canal text not null, -- cflogistica | skydropx
  estado text not null default 'Generada', -- Generada | Enviada a almacen | Reimpresa
  archivo_nombre text,
  archivo_ruta text,
  shipment_id text,
  label_url text,
  tracking_number text,
  tracking_url text,
  costo_total numeric,
  override_duplicado boolean not null default false,
  created_at timestamptz default now()
);

alter table public.guias_historial add column if not exists tracking_number text;
alter table public.guias_historial add column if not exists tracking_url text;
alter table public.guias_historial add column if not exists costo_total numeric;
alter table public.guias_historial add column if not exists shipment_id text;

create index if not exists idx_guias_historial_pedido on public.guias_historial (pedido);
create index if not exists idx_guias_historial_created_at on public.guias_historial (created_at);

alter table public.guias_historial enable row level security;

drop policy if exists "Allow all for guias_historial" on public.guias_historial;
create policy "Allow all for guias_historial"
  on public.guias_historial for all
  using (true)
  with check (true);
